### ISSUE TITLE
Stack fails because of an access issue

### ISSUE THREAD

**Issue by reena-cs** [build-on-aws/workflow-orchestration-bedrock-agent-chaining#3]
Received response status [FAILED] from custom resource.
 Message returned: Error: An error occurred (AccessDeniedException) when calling the CreateKnowledgeBase operation: 
User: arn:aws:sts::xxxxxxxxxxx:assumed-role/WorkflowOrchestrationBedr-BedrockCRProviderCRRole90-BuXII2KBRTcl/WorkflowOrchestrationBedr-BedrockCRProviderCustomR-yWdcVeLmWk56 is not authorized to perform: bedrock:CreateKnowledgeBase on resource: arn:aws:bedrock:ap-south-1:xxxxxxxxxx:knowledge-base/* 
Logs: /aws/lambda/WorkflowOrchestrationBedr-BedrockCRProviderCustomR-yWdcVeLmWk56 at invokeUserFunction (/var/task/framework.js:2:6) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async onEvent (/var/task/framework.js:1:369) at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 78fe1451-9271-4dcc-8fd9-fe3b2035c94b)

**Comment by pkamra** [comment]
Updated stack.
